#!/bin/sh -ex
# main installation script
#
# Install Ubiquiti's Unifi Controller on Debian/Ubuntu
#

# Get release name
release=$( lsb_release -sc )

# Install apt keys for Ubiquiti and Mongodb repos
apt-key adv --keyserver keyserver.ubuntu.com --recv 06E85760C0A52C50
#apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10

# Ensure that non-free packages are available
sed -i -e "/non-free/ s/^#\s*//" /etc/apt/sources.list.d/sources.list

# Install packages
apt-get -q update
apt-get -qy install unifi

# Stop services
service unifi stop
service mongodb stop

# Patch init.d/unifi
#sed -i 's/^JAVA_HOME=.*$/JAVA_HOME="$( readlink -f "$( which java )" | sed "s:bin/.*$::" )"/' /etc/init.d/unifi

